spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app
    username: jakub
    password: jakub
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  job:
    cron-customer-risk-calculation: 0 0 20 * * ?
  file:
    location: /Users/jakubperzanowski/Desktop/CustomDirectory
email:
  address:
    directors: dyrektorjednostki@fikcyjnafirma.com
    coordinators: koordynatorkoordynatorow@fikcyjnafirma.com
  message:
    typeA5-type1: Uprzejmie informuję, że zmieniła się klasa ryzyka dla klienta
    type2: Proszę o przegląd ryzyka klienta
